$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$fontDir = Join-Path $root 'assets\fonts'
$cssFile = Join-Path $root 'css\fonts.css'
New-Item -ItemType Directory -Force -Path $fontDir | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $cssFile) | Out-Null

$families = @(
  'family=Montserrat:wght@600;700',
  'family=Open+Sans:wght@400;600'
)
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
$url = 'https://fonts.googleapis.com/css2?' + ($families -join '&') + '&display=swap'

$css = (Invoke-WebRequest -Uri $url -Headers @{ 'User-Agent' = $ua } -UseBasicParsing).Content

$blocks = [regex]::Matches($css, '@font-face\s*{(?s)(.*?)}')
$out = @()
$out += '/* Self-hosted latin subsets - generated by scripts/fetch-fonts.ps1 */'
$out += ''

foreach ($m in $blocks) {
  $body = $m.Groups[1].Value
  $family = [regex]::Match($body, 'font-family:\s*(?:\x27|\x22)?([^\x27\x22;]+?)(?:\x27|\x22)?;').Groups[1].Value.Trim()
  $weight = [regex]::Match($body, 'font-weight:\s*(\d+)').Groups[1].Value
  $style = [regex]::Match($body, 'font-style:\s*(\w+)').Groups[1].Value
  $range = [regex]::Match($body, 'unicode-range:\s*([^;]+);').Groups[1].Value.Trim()
  $src = [regex]::Match($body, 'url\((https://[^)]+\.woff2)\)').Groups[1].Value

  # Only latin subset block
  if ($range -notmatch 'U\+0000-00FF') { continue }

  $file = ($family -replace '\s+', '-') + '-' + $weight + '.woff2'
  Invoke-WebRequest -Uri $src -OutFile (Join-Path $fontDir $file) -UseBasicParsing

  $out += "@font-face {"
  $out += "  font-family: '$family';"
  $out += "  font-style: $style;"
  $out += "  font-weight: $weight;"
  $out += "  font-display: swap;"
  $out += "  src: url('../assets/fonts/$file') format('woff2');"
  $out += "  unicode-range: $range;"
  $out += "}"
  $out += ""
}

Set-Content -Path $cssFile -Value $out -Encoding UTF8
Write-Output "fonts written to $cssFile"
Get-ChildItem $fontDir | Select-Object Name, Length